https://www.youtube.com/watch?v=GIsg-ZUy0MY

In [1]:
import torch

# BASICS

In [2]:
# Number
t1 = torch.tensor(4.)
t1

tensor(4.)

In [3]:
t1.dtype 

torch.float32

In [4]:
# Vector
t2 = torch.tensor([1.,2,3,4])
t2

# If we provide different datatype then pytorch will convert it to same datatype

tensor([1., 2., 3., 4.])

In [6]:
# Matrix
t3 = torch.tensor([[5.,6],[7,8],[9,10]])
# t3 = torch.tensor([[5.,6],[7,8],[9,10]]) This gives an error
t3

tensor([[ 5.,  6.],
        [ 7.,  8.],
        [ 9., 10.]])

In [8]:
# 3-dimentional array

t4 = torch.tensor([
    [[11,12,13],
     [13,14,15]],
    [[15,16,17],
     [17,18,19.]]
])
t4

tensor([[[11., 12., 13.],
         [13., 14., 15.]],

        [[15., 16., 17.],
         [17., 18., 19.]]])

In [9]:
t1.shape

torch.Size([])

In [10]:
t2.shape

torch.Size([4])

## Tensor operations and gradients
We can combine tensors with the usual arithmetic operations.

In [11]:
# Create tensors.
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad=True) 
b = torch.tensor(5.,requires_grad=True)

The x,w,b are all tensors(which are numbers). w abd b hava an additional parameter requires_grad set to True.

In [12]:
# Combining tensors
y = w*x+b
y

tensor(17., grad_fn=<AddBackward0>)

What makes pytorch special is that we can automatically compute the derivative of y w.r.t the tensors that have requires_grad set to True i.e w and b. To compute the derivatives, we can call the .backward method on our result y.

In [13]:
# Compute derivative
y.backward()

The derivatives of y w.r.t the input tensors are stored in the .grad property of the respective tensors.

In [14]:
# Display gradients
print('dy/dx', x.grad)
print('dy/dw', w.grad)
print('dy/db', b.grad)

dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


The "grad" in w.grad stands for gradient, which is another term for derivative, used mainly when dealing with matrices.

Note: Gradient is used mainly when dealing with matrices and derivative is mainly used when dealing with numbers

## Interoperability with Numpy
Numpy, Matplotlib, openCV, Pandas

In [15]:
import numpy as np

x = np.array([[1,2],[3,4.]]) # Creating an array in numpy
x

array([[1., 2.],
       [3., 4.]])

We can convert a Numpy array to a Pytorch tensor using torch.from_numpy

In [16]:
# Convert th enumpy array to a torch tensor
y = torch.from_numpy(x)
y


# or
# y = torch.tensor(x)

# The difference is that torch.from_numpy uses the same space and memory while other creates a copy of the daat


tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [17]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

We can convert a PyTorch tensor to a Numpy array using th .numpy method of a tensor.

In [18]:
# Convert a torch tensor to a numpy array
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])

The interoperability between PyTorch and Numpy is really important because most datasets you work with will likely be read and processed as Numpy arrays.

numpy vs torch

for cuda and gpu 